Merge from SHADE-AI upstream
ALLAN-DIP/diplomacy pull request #21
Opened 2023-07-29 00:12 UTC by aphedges

This is my best attempt at merging the changes from <https://github.com/SHADE-AI/diplomacy> into our fork. It might not work properly because I'm not sure how to test it, I'm not familiar with the codebase, and I don't know what all of the expected behavior is, so feedback would be greatly appreciated!

I'll try to test it with some ALLAN bots, but I figured I should have you look at it early so you can let me know if I messed anything important up.

2023-07-29 06:12 UTC, SiddarGu requested changes
No obvious problems except incompatible dependencies.

2023-07-29 06:12 UTC, SiddarGu commented on diplomacy/web/package.json
Can you bump `react` and `react-dom` to ^17.0.0? The current version is not compatible with `@mui/material`. Please also remove the duplicate `prop-types`.

2023-07-31 22:30 UTC, aphedges commented on diplomacy/web/package.json
I needed to use `npm install --force` to get installation to work, and from the lock file, this is clearly what SHADE is using as well.

I tried updating to React 17, but it causes conflicts that require other version changes, which themselves cause build failures. The application is complex, so I'd rather not run an upgrade without a good way to test everything.

I can remove the duplicate `prop-types`, though.

2023-07-31 22:36 UTC, SiddarGu commented on diplomacy/web/package.json
Weird. I was able to do that without conflict.

2023-07-31 22:37 UTC, SiddarGu commented on diplomacy/web/package.json
Have u tried removing node modules and package lock and doing a clean install?

2023-07-31 22:41 UTC, aphedges commented on diplomacy/web/package.json
I did. It might have just be build warnings instead of build errors, but they were still something that didn't seem like a good idea to ignore.

Regardless, I think that we should stay on the same dependencies as SHADE unless a change is needed. We could upgrade to newer versions of our dependencies, but I don't think our limited time is worth the effort when we have more important things to do.

2023-08-01 19:06 UTC, aphedges commented on diplomacy/web/package.json
@SiddarGu, thoughts on this?

2023-08-05 16:11 UTC, SiddarGu approved these changes

2023-08-08 01:52 UTC, merged